import type { ScrapedEvent } from "./base";

const SOURCE_NAME = "Sydney Events Hub";
const SOURCE_URL = "https://whatson.cityofsydney.nsw.gov.au/events";

// Generates realistic Sydney events with future dates for seeding/demo
export function generateSeedEvents(): ScrapedEvent[] {
  const now = new Date();
  const addDays = (d: Date, n: number) => new Date(d.getTime() + n * 86400000);
  const fmt = (d: Date) => d.toISOString();

  const events: ScrapedEvent[] = [
    {
      title: "Vivid Sydney – Lights, Music & Ideas Festival",
      date_time: fmt(addDays(now, 5)),
      date_time_end: fmt(addDays(now, 25)),
      venue_name: "Circular Quay & Sydney Harbour",
      venue_address: "Circular Quay, Sydney NSW 2000",
      city: "Sydney",
      description: "Vivid Sydney is the world's largest festival of light, music and ideas. Spectacular light sculptures and projections transform the city.",
      category: "Festival",
      tags: ["Festival", "Lights", "Music", "Art"],
      image_url: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
      source_name: SOURCE_NAME,
      source_url: SOURCE_URL,
      original_event_url: "https://www.vividsydney.com",
    },
    {
      title: "Sydney Opera House: Orchestra Concert",
      date_time: fmt(addDays(now, 3)),
      date_time_end: fmt(new Date(addDays(now, 3).getTime() + 2.5 * 3600000)),
      venue_name: "Sydney Opera House",
      venue_address: "Bennelong Point, Sydney NSW 2000",
      city: "Sydney",
      description: "An unforgettable evening of classical music performed by the Sydney Symphony Orchestra in the iconic Concert Hall.",
      category: "Music",
      tags: ["Music", "Classical", "Orchestra", "Arts"],
      image_url: "https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?w=800&q=80",
      source_name: SOURCE_NAME,
      source_url: SOURCE_URL,
      original_event_url: "https://www.sydneyoperahouse.com/events",
    },
    {
      title: "Bondi Beach Yoga & Wellness Weekend",
      date_time: fmt(addDays(now, 7)),
      date_time_end: fmt(addDays(now, 8)),
      venue_name: "Bondi Beach Pavilion",
      venue_address: "Queen Elizabeth Dr, Bondi Beach NSW 2026",
      city: "Sydney",
      description: "Join hundreds of yogis on the iconic Bondi Beach for a weekend of sunrise yoga, wellness workshops, and meditation sessions.",
      category: "Health & Wellness",
      tags: ["Yoga", "Wellness", "Beach", "Meditation"],
      image_url: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&q=80",
      source_name: SOURCE_NAME,
      source_url: SOURCE_URL,
      original_event_url: "https://www.eventbrite.com.au/d/australia--sydney/yoga",
    },
    {
      title: "Sydney Night Noodle Markets",
      date_time: fmt(addDays(now, 10)),
      date_time_end: fmt(addDays(now, 20)),
      venue_name: "Hyde Park",
      venue_address: "Hyde Park, Sydney NSW 2000",
      city: "Sydney",
      description: "Sydney's beloved Night Noodle Markets return to Hyde Park with hundreds of delicious Asian street food stalls, live music and entertainment.",
      category: "Food & Drink",
      tags: ["Food", "Night Market", "Asian Cuisine", "Street Food"],
      image_url: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&q=80",
      source_name: SOURCE_NAME,
      source_url: SOURCE_URL,
      original_event_url: "https://www.timeout.com/sydney/food/night-noodle-markets",
    },
    {
      title: "Darling Harbour NYE Fireworks & Countdown",
      date_time: fmt(addDays(now, 14)),
      date_time_end: fmt(new Date(addDays(now, 14).getTime() + 4 * 3600000)),
      venue_name: "Darling Harbour",
      venue_address: "Darling Harbour, Sydney NSW 2000",
      city: "Sydney",
      description: "Ring in the New Year with a spectacular fireworks display over Darling Harbour, with family fireworks at 9pm and midnight grand finale.",
      category: "Celebration",
      tags: ["Fireworks", "New Year", "Family", "Free"],
      image_url: "https://images.unsplash.com/photo-1467810563316-b5476525c0f9?w=800&q=80",
      source_name: SOURCE_NAME,
      source_url: SOURCE_URL,
      original_event_url: "https://www.darlingharbour.com/events",
    },
    {
      title: "Art Gallery of NSW – Contemporary Australian Art",
      date_time: fmt(addDays(now, 1)),
      date_time_end: fmt(addDays(now, 60)),
      venue_name: "Art Gallery of NSW",
      venue_address: "Art Gallery Rd, Sydney NSW 2000",
      city: "Sydney",
      description: "Explore the latest contemporary Australian art exhibition featuring works from emerging and established artists across painting, sculpture and digital media.",
      category: "Art",
      tags: ["Art", "Exhibition", "Gallery", "Contemporary"],
      image_url: "https://images.unsplash.com/photo-1485083269755-a7b559a4fe5e?w=800&q=80",
      source_name: SOURCE_NAME,
      source_url: SOURCE_URL,
      original_event_url: "https://www.artgallery.nsw.gov.au/exhibitions",
    },
    {
      title: "Sydney Farmers Market – Pyrmont",
      date_time: fmt(addDays(now, 2)),
      date_time_end: fmt(new Date(addDays(now, 2).getTime() + 4 * 3600000)),
      venue_name: "Pyrmont Bridge Road",
      venue_address: "Pyrmont Bridge Rd, Pyrmont NSW 2009",
      city: "Sydney",
      description: "Fresh produce, artisan goods, and local specialty foods from farmers across NSW. Every Saturday morning.",
      category: "Food & Drink",
      tags: ["Market", "Food", "Organic", "Local"],
      image_url: "https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=800&q=80",
      source_name: SOURCE_NAME,
      source_url: SOURCE_URL,
      original_event_url: "https://www.cityofsydney.nsw.gov.au/events/markets",
    },
    {
      title: "TEDx Sydney 2026 – Ideas Worth Spreading",
      date_time: fmt(addDays(now, 18)),
      date_time_end: fmt(new Date(addDays(now, 18).getTime() + 8 * 3600000)),
      venue_name: "International Convention Centre Sydney",
      venue_address: "14 Darling Dr, Sydney NSW 2000",
      city: "Sydney",
      description: "TEDx Sydney returns with inspiring talks from local and international speakers across technology, science, arts and social innovation.",
      category: "Conference",
      tags: ["TED", "Technology", "Innovation", "Conference"],
      image_url: "https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=800&q=80",
      source_name: SOURCE_NAME,
      source_url: SOURCE_URL,
      original_event_url: "https://www.tedxsydney.com",
    },
    {
      title: "Harbour City Summer Swim Classic",
      date_time: fmt(addDays(now, 4)),
      date_time_end: fmt(new Date(addDays(now, 4).getTime() + 6 * 3600000)),
      venue_name: "North Sydney Olympic Pool",
      venue_address: "4 Walker St, Milsons Point NSW 2061",
      city: "Sydney",
      description: "Annual open-water swimming competition in Sydney Harbour. All levels welcome. Stunning views of the Sydney Harbour Bridge and Opera House.",
      category: "Sport",
      tags: ["Swimming", "Sport", "Harbour", "Competition"],
      image_url: "https://images.unsplash.com/photo-1530549387789-4c1017266635?w=800&q=80",
      source_name: SOURCE_NAME,
      source_url: SOURCE_URL,
      original_event_url: "https://www.eventbrite.com.au/d/australia--sydney/sports",
    },
    {
      title: "Mardi Gras: Sydney WorldPride Film Festival",
      date_time: fmt(addDays(now, 22)),
      date_time_end: fmt(addDays(now, 32)),
      venue_name: "Event Cinemas George Street",
      venue_address: "505 George St, Sydney NSW 2000",
      city: "Sydney",
      description: "A celebration of LGBTQIA+ cinema from around the world, screening over 50 films across 10 days during Mardi Gras season.",
      category: "Film",
      tags: ["Film", "LGBTQIA+", "Mardi Gras", "Festival"],
      image_url: "https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=800&q=80",
      source_name: SOURCE_NAME,
      source_url: SOURCE_URL,
      original_event_url: "https://www.mardi.gras.org.au",
    },
    {
      title: "Surry Hills Creative Precinct Open Day",
      date_time: fmt(addDays(now, 6)),
      date_time_end: fmt(new Date(addDays(now, 6).getTime() + 8 * 3600000)),
      venue_name: "Surry Hills Creative Precinct",
      venue_address: "702 Elizabeth St, Surry Hills NSW 2010",
      city: "Sydney",
      description: "Explore the studios, galleries and creative spaces of Surry Hills during this free open-day event with live demonstrations and artist talks.",
      category: "Art",
      tags: ["Art", "Design", "Free", "Community"],
      image_url: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=800&q=80",
      source_name: SOURCE_NAME,
      source_url: SOURCE_URL,
      original_event_url: "https://www.cityofsydney.nsw.gov.au/arts-culture",
    },
    {
      title: "Sydney Startup Week: Innovation Summit",
      date_time: fmt(addDays(now, 12)),
      date_time_end: fmt(addDays(now, 16)),
      venue_name: "Fishburners",
      venue_address: "11 York St, Sydney NSW 2000",
      city: "Sydney",
      description: "Five days of workshops, panels and networking events connecting Sydney's startup and innovation ecosystem. Featuring investors, founders and mentors.",
      category: "Business",
      tags: ["Startup", "Business", "Networking", "Technology"],
      image_url: "https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=800&q=80",
      source_name: SOURCE_NAME,
      source_url: SOURCE_URL,
      original_event_url: "https://sydneystartupweek.com",
    },
  ];

  return events;
}
